mysite/bands/urls.py
from django.urls import path
from bands import views as b_views

# On donne un nom à l'app
app_name = "bands"
urlpatterns = [
    path('', b_views.bands, name='index'),
    path('<int:band_id>/', b_views.band_detail, name='detail'),
    path('bandAdd', b_views.bandAdd, name='bandAdd' ),
    path('bandUp', b_views.bandUp, name='bandUp' ),
]

mysite/listings/urls.py
from django.urls import path
from listings import views

app_name = 'listings'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>', views.detail, name='detail'),
    path('add', views.add, name='add'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as m_views

# Tout les urls
urlpatterns = [
    path('admin/', admin.site.urls),
    # On donne des petits noms au urls pour plus facilement les retrouver
    path('', m_views.index, name='index'),
    path('a-propos/', m_views.about, name='about'),
    path('about2/', m_views.about2),
    # Dès qu'un url commence par /bands/ est détecté,
    # il va chercher dans le fichier urls.py dans l'app bands un url qui correspond à l'actuel
    path('bands/', include('bands.urls')),
    path('listings/', include('listings.urls')),
]

mysite/bands/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.


class Band(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateField()
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.created_at}"

class BandsAdd(models.Model):
    class BandsType(models.TextChoices):
        RAP = 'Rap'
        Rock = 'Rock'
        Falk = 'Falk'
        OTHER = 'Other'

    name = models.CharField(max_length=20)
    active = models.BooleanField(default=False)
    description = models.TextField(max_length= 1000, default='description')
    bands_type = models.CharField(max_length=20, choices=BandsType.choices)
    band = models.ForeignKey(Band, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}"

class BandsUp(models.Model):
    class BandsType(models.TextChoices):
        RAP = 'Rap'
        Rock = 'Rock'
        Falk = 'Falk'
        OTHER = 'Other'

    class BandsNameUp(models.TextChoices):
        name = BandsAdd.objects.get(id=band_id)

    name = models.CharField(max_length=20)
    active = models.BooleanField(default=False)
    description = models.TextField(max_length= 1000, default='description')
    bands_type = models.CharField(max_length=20, choices=BandsType.choices)
    band = models.ForeignKey(Band, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}"

mysite/listings/models.py
from django.db import models
from bands.models import Band
# Create your models here.


class Listing(models.Model):

    class ListingType(models.TextChoices):
        CLOTH = 'C'
        MUSIC = 'M'
        BOOK = 'B'
        OTHER = 'O'

    name = models.CharField(max_length=20)
    description = models.TextField(max_length=200)
    price = models.IntegerField()
    is_sold = models.BooleanField(default=False)
    listing_type = models.CharField(max_length=1, choices=ListingType.choices)
    band = models.ForeignKey(Band, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f"{self.name}"

mysite/main/models.py
from django.db import models

# Create your models here.

mysite/listings/forms.py
from django import forms
from listings.models import Listing


class ListingForm(forms.ModelForm):

    class Meta:
        model = Listing
        fields = ['name', 'description', 'price', 'listing_type', 'band']

mysite/bands/views.py
from django.shortcuts import render, redirect
from bands.models import Band
from bands.models import BandsAdd
from bands.form import bandForm
# Create your views here.


def bands(request):
    # Récupérer toutes les groupes
    bands = BandsAdd.objects.all()

    context = {
        'bands': bands
    }
    return render(request, 'bands/bands.html', context)


def band_detail(request, band_id):
    # Récupérer un groupe en particulier grâce à son id (clé primaire)
    band = BandsAdd.objects.get(id=band_id)
    context = {'band': band}

    if request.method == 'POST':
        band.delete()
        return redirect('bands:index')

    

    return render(request, 'bands/band_detail.html', context)


def bandAdd(request):
    form = bandForm()
    if request.method == 'POST':
        form = bandForm(request.POST)
        if form.is_valid():
            form.save()
            print('save')
            return redirect('bands:index')

    context = {
        'form': form
    }
    return render(request, 'bands/band_add.html', context)

def bandUp(request):
    form = bandForm()
    if request.method == 'POST':
        form = bandForm(request.POST)
        if form.is_valid():
            form.save()
            print('save')
            return redirect('bands:index')

    context = {
        'form': form
    }
    return render(request, 'bands/bandUp.html', context)

mysite/listings/views.py
from django.shortcuts import render, redirect
from listings.models import Listing
from listings.forms import ListingForm
# Create your views here.


def index(request):
    listings = Listing.objects.all()
    context = {
        'listingList': listings
    }
    return render(request, 'listings/index.html', context)


def detail(request, id):
    listing = Listing.objects.get(id=id)
    context = {
        'listing': listing
    }
    return render(request, 'listings/detail.html', context)


def add(request):
    form = ListingForm()
    if request.method == 'POST':
        form = ListingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listings:index')

    context = {
        'form': form
    }
    return render(request, 'listings/add.html', context)

mysite/main/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context = {
        'title': "Home",
    }
    return render(request, 'main/index.html', context)


def about(request):
    isAdmin = True
    first_name = "John"
    last_name = "Doe"
    context = {
        'isAdmin': isAdmin,
        'first_name': first_name,
        'last_name': last_name,
    }
    return render(request, 'main/about.html', context)


def about2(request):
    isAdmin = True
    first_name = "John"
    last_name = "Doe"
    if isAdmin:
        content = f"""
        <h1> {first_name} - {last_name} </h1>
        <p> Lorem ipsum dolor, sit amet consectetur adipisicing elit. Labore iste voluptas animi id, cupiditate quisquam
        nulla qui laborum harum impedit. </p>
        """
    else:
        content = "<p>C'est toi. Tu ne sais pas qui tu es ?</p>"
    context = {
        'content': content,
    }
    return render(request, 'main/about2.html', context)

mysite/bands/templates/bands/bandUp.html
{% extends 'main/_base.html' %}

{% block title %}Modifier un groupe{% endblock title %}

{% block content %}
<h1>Modifier un groupe</h1>
<form action="" method="post">

    {% csrf_token %}

    {{form.as_p}}

    <button type="submit">Envoyer</button>
</form>
{% endblock content %}

mysite/bands/templates/bands/band_add.html
{% extends 'main/_base.html' %}

{% block title %}Ajouter un groupe{% endblock title %}

{% block content %}
<h1>Ajouter un groupe</h1>
<form action="" method="post">

    {% csrf_token %}

    {{form.as_p}}

    <button type="submit">Envoyer</button>
</form>
{% endblock content %}

mysite/bands/templates/bands/band_detail.html
{% extends 'main/_base.html' %}

{% block title %}{{band.name}}{% endblock title %}

{% block content %}
<h1>{{band.name}}</h1>
<p>{{band.description}}</p>
<p>{{band.bands_type}}</p>
<p>Créé le : {{band.created_at}}</p>

{% comment %} créer formulaire {% endcomment %}
<form action="" method="post">
    {% csrf_token %}
    {% comment %} créer bouton {% endcomment %}
    <input type="submit" value="Supprimer">
</form>

{% endblock content %}

mysite/bands/templates/bands/bands.html
{% extends 'main/_base.html' %}

{% block title %}Groupe{% endblock title %}

{% block content %}
<h1>Les groupes</h1>

<ul>
  {% for band in bands %}
  <li><a href="{% url 'bands:detail' band.id %}">{{band.name}}</a></li>
  {% endfor %}
</ul>

{% endblock content %}

mysite/listings/templates/listings/add.html
{% extends 'main/_base.html' %}

{% block title %}Ajouter une annonce{% endblock title %}

{% block content %}
<h1>Ajouter une annonce</h1>
<form action="" method="post">

  {% csrf_token %}

  {{form.as_p}}

  <button type="submit">Envoyer</button>
</form>
{% endblock content %}

mysite/listings/templates/listings/detail.html
{% extends 'main/_base.html' %}

{% block title %}{{listing.name}}{% endblock title %}

{% block content %}
<h1>{{listing.name}}</h1>
<p>{{listing.description}}</p>
<p>{{listing.price}}</p>
{% endblock content %}

mysite/listings/templates/listings/index.html
{% extends 'main/_base.html' %}

{% block title %}Annonces{% endblock title %}

{% block content %}
<h1>Les annonces</h1>

<ul>
  {% for listing in listingList %}
  <li>{{listing.price}}€ - {{listing.name}} -
    <a href="{% url 'listings:detail' listing.id%}">Afficher</a>
  </li>
  {% endfor %}
</ul>
{% endblock content %}

mysite/main/templates/main/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'main/style.css' %}">
  <title>{% block title %}Base !{% endblock %}</title>
</head>

<body>
  <nav>
    <ul>
      <li><a href="{% url 'index' %}">Accueil</a></li>
      <li><a href="{% url 'bands:index' %}">Les groupes</a></li>
      <li><a href="{% url 'about' %}">A propos</a></li>
      <li><a href="{% url 'listings:index' %}">Annonces</a></li>
      <li><a href="{% url 'listings:add' %}">Ajouter un annonces</a></li>
      <li><a href="{% url 'bands:bandAdd' %}">Ajouter un groupe</a></li>
      <li><a href="{% url 'bands:bandUp' %}">Modifier un groupe</a></li>
    </ul>
  </nav>
  {% block content %}{% endblock%}
</body>

</html>

mysite/main/templates/main/about.html
{% extends 'main/_base.html' %}

{% block title %}
A propos
{% endblock title %}

{% block content %}

{% if not isAdmin %}
<h1>{{first_name}} - {{last_name}}</h1>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Labore iste voluptas animi id, cupiditate quisquam
  nulla qui laborum harum impedit.</p>
{% else %}
<p>C'est toi. Tu ne sais pas qui tu es ?</p>
{% endif %}

{% endblock content %}

mysite/main/templates/main/about2.html
{% extends 'main/_base.html' %}

{% block title %}
A propos
{% endblock title %}

{% block content %}

{{content|safe}}
{% endblock content %}

mysite/main/templates/main/index.html
{% extends 'main/_base.html' %}
{% load static %}

{% block title %}Accueil{% endblock title %}

{% block content %}
<h1>{{title}}</h1>
<ul>
  <li>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque, perspiciatis?</li>
  <li>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, architecto?</li>
  <li>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis, architecto?</li>
</ul>
<img src="{% static 'main/img/elephant.jpg' %}" alt="">
{% endblock content %}